[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
